version: '3.9'

volumes:
    postgre-db:

services:
    db:
        image: postgres:latest
        restart: always
        volumes:
            - postgre-db:/var/lib/postgresql/data
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdata
            - POSTGRES_USER=$DB_USER
            - POSTGRES_PASSWORD=$DB_PASSWORD
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
        expose:
            - "5432"
    backend:
        build: backend
        expose:
            - "8080"
        environment:
            - DB_HOST=5432
            - DB_USER=$DB_USER
            - DB_PASS=$DB_PASSWORD
            - DB_NAME=postgres
        volumes:
            - postgre-db:/home/appuser
        restart: always
        depends_on:
            - db
            - reverseproxy
    reverseproxy:
        build: nginx
        volumes:
            - "${BLUXE_KEY}:/etc/ssl/private"
    # frontend:
    #     build: frontend
    #     expose:
    #         - 8080
    #     restart: always
    #     depends_on:
    #         - reverseproxy
